# Generated by Django 5.0.6 on 2024-07-06 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_appointment_doctor_alter_appointment_patient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='last_updated',
            new_name='date',
        ),
    ]
