# Generated by Django 5.0.6 on 2024-07-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_appointment_date_appointment_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
