# Generated by Django 5.0.6 on 2024-07-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='date',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='details',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patient',
        ),
        migrations.AddField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='prescription',
            name='duration',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Scheduled', 'Scheduled'), ('Rescheduled', 'Rescheduled'), ('Canceled', 'Canceled'), ('Completed', 'Completed')], default='Scheduled', max_length=50),
        ),
    ]
