# Generated by Django 5.0.6 on 2024-07-06 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_prescription_doctor_alter_prescription_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='doctor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='core.doctor'),
        ),
    ]
