# Generated by Django 5.0.6 on 2024-07-06 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_billing_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.doctor'),
        ),
    ]
